name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: Testing
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - name: "Get the repository content"
      uses: actions/checkout@v1

    - name: Enable version ${{ matrix.python-version }} of Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependecies
      run: python -m pip install -r test-requirements.txt

    - name: Check format
      run: |
        black --check pyoppversion/*
        black --check tests/*

    - name: Run tests
      run: python -m pytest -v